### ISSUE TITLE
Set sender one of the recipient by Default 

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Tessercube-iOS#1]
If Alice send Bob sth by Tessercube keyboard, Alice should able to decrypt the msg herself by default, right?

The performance of current ios 1.0(6) ver is inconsist (for inApp compose and compose through keyboard)

**Comment by Tedko** [comment]
> Please report bugs to respective platform-specific repositories.

@neruthes transferred

**Comment by neruthes** [comment]
Alright, I just looked through it again and figured out that this should be a question and shall no longer relevant with the upcoming Settings page. Thank you for your participation anyway. :)

**Comment by Tedko** [comment]
Fixed by iOS side
