### ISSUE TITLE
Importing multiple contacts at once not possible if first contact already exists

### ISSUE THREAD

**Issue by sigttou** [DimensionDev/Tessercube-iOS#117]
When importing a public key file with multiple users the import says Already added, even if one of the accounts is not in the list yet.

Steps to reproduce:
export 5 contacts from GPG to file -> copy file to tessercube to import, 5 contacts are added correctly.
export those 5 contacts again + 1 new from GPG to file -> copy file to tessercube, says accounts are added but the new one is missing

expected behavior: see all 6 contacts in contact list.

**Comment by sigttou** [comment]
If first doesn't exist, the contacts are added, but ending up with 11 accounts, having 5 duplicates.

**Comment by neruthes** [comment]
Thanks for the report. 👍

**Comment by MainasuK** [comment]
WIP

**Comment by MainasuK** [comment]
Bugfix will release in the 1.3.4. That's would not wait too long for Apple approve the update. And I highly recommend remove the contacts you previous imported. Then re-import the armor again.

Thank your for your bug report. You can reopen that issue if problem still existing in 1.3.4.
