### ISSUE TITLE
iOS crash when importing public key

### ISSUE THREAD

**Issue by dbarella** [DimensionDev/Tessercube-iOS#119]
Hey y'all,

First off, great app! I really appreciate the effort to make a good UI for good encryption ^_^

I'm running into a bug when trying to import someone else's public key -- both were generated within tessercube iOS apps, both the same (most recent from app store) version. I don't have a crash log. But what happens is:

- Copy public key shared by my friend (the whole message was generated by tessercube, no copy/paste)
- Go to contacts
- Hit `+` to add a new contact
- Tessercube automatically uses the contents of the copy buffer
- Hit 'Import keypair"
- Immediate application crash, returning to home screen.

On relaunch the contact has not been added, so something is going wrong when adding the public key, not after.

**Comment by MainasuK** [comment]
Fixed a related issue. Please try again to see if the problem resolved.

**Comment by dbarella** [comment]
Yup, that fixed it! Thanks ^_^

**Comment by yisiliu** [comment]
Sounds great ;)

**Comment by neruthes** [comment]
Good news 🥳
