### ISSUE TITLE
The return button should detect the context of the current input field

### ISSUE THREAD

**Issue by MainasuK** [DimensionDev/Tessercube-iOS#13]
See the following pics:
<img src="https://i.imgur.com/pbAhASw.jpg" alt="drawing" width="200"/><img src="https://i.imgur.com/KNjHfb1.jpg" alt="drawing" width="200"/>

Should use ‘search’

**Comment by Tedko** [comment]
For BD purpose i need this to be fixed soon.

**Comment by MainasuK** [comment]
Fixed in version 1.3.2 (37)
