### ISSUE TITLE
Navigation Bar left item duplicate when push under contacts search mode

### ISSUE THREAD

**Issue by MainasuK** [DimensionDev/Tessercube-iOS#17]
1. Tap search bar and type Dan
2. Tap the 'Dan' cell and push to contact detail view

![Simulator Screen Shot - iPhone 8 Plus - 2019-06-18 at 18 44 29](https://user-images.githubusercontent.com/7940186/59676006-20854580-91f9-11e9-854d-40fc555bae8c.png)

**Comment by Tedko** [comment]
Tested on the latest Testflight Ver. Solved.
