### ISSUE TITLE
Crash when delete the pri/pub keypair in Contacts

### ISSUE THREAD

**Issue by MainasuK** [DimensionDev/Tessercube-iOS#18]
1. Tap the *bold* contact cell push into contact detail view.
2. Tap Edit. Tap Delete.
3. Confirm delete whole key pair.
4. Crash in some condition .

Can not reproduce the bug and not get any crash report for that.
Any similarity crash related with that please commit here.

**Comment by Tedko** [comment]
Tested on Testflight (20). Problem fixed.
