### ISSUE TITLE
Support Strong Password

### ISSUE THREAD

**Issue by ihubgit** [DimensionDev/Tessercube-iOS#2]
hi I'm using version 1.0 (5) and am stuck in the stage of creating a key pair. Running iOS 12.2. After entering wished username and password I'm getting the following error :
Password should be minimum 8 characters at least 1 Alphabet and 1 number
Now my password respects these conditions and yet no way to move onward ...

PS : how can i update to latest version if there is one ?

**Comment by Tedko** [comment]
@neruthes transferred to iOS repo. will check condition of Android ver latter

**Comment by Tedko** [comment]
Fixed in the 1st App Store version
