### ISSUE TITLE
Clear text input normalization

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Tessercube-iOS#4]
We shall have the following normalization policy:

- Leading spacing characters are all trimmed.
- Trailing spacing characters are all trimmed, but a linebreak is appended.

Spacing characters include space, zero-width space, full-width space, tab, CR, LF, CRLF, etc.

**Comment by neruthes** [comment]
<img width="588" alt="Screen Shot 2019-05-08 at 09 03 31" src="https://user-images.githubusercontent.com/2139261/57363226-2c003e00-7170-11e9-9fae-c7266db13991.png">

**Comment by MainasuK** [comment]
That's should works after release 1.0.0. 

Closed and reopen if have any issue with that.
