### ISSUE TITLE
Reduce the App size 

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Tessercube-iOS#45]
The latest Google Play ver for tessercube is 23MB, however for iOS it's 209MB.

We need to find ways to optimized the size of the App, for better user experience, and BD etc.

**Comment by jk234ert** [comment]
Plan to archive a go-mobile powered version to compare the package size.

Once we confirm that the go-mobile version is much smaller & can work properly, we will concentrate on the migration to the go-mobile version.

**Comment by jk234ert** [comment]
In TestFlight 1.1.5(25), app size reduced to ~110MB by using DMSGoPGP instead of BouncyCastle+j2objc

**Comment by jk234ert** [comment]
In TestFlight 1.1.5(26), app size reduced to ~86MB by using DMSGoPGP compiled using latest Go & gomobile branch
Go version: `go version devel +b36a7a502a Mon Sep 2 21:46:03 2019 +0000 darwin/amd64`

**Comment by Tedko** [comment]
> In TestFlight 1.1.5(26), app size reduced to ~86MB by using DMSGoPGP compiled using latest Go & gomobile branch
> Go version: `go version devel +b36a7a502a Mon Sep 2 21:46:03 2019 +0000 darwin/amd64`

👍🏻

**Comment by MainasuK** [comment]
Resolve in version 1.3.0 (35) 

Download size: ~141MB to ~69.2MB
Install size: ~226MB to ~113MB
