### ISSUE TITLE
Fail to create private key via GoPGP 

### ISSUE THREAD

**Issue by MainasuK** [DimensionDev/Tessercube-iOS#49]
Can not create private PGP key:

- Clean install.
- RSA 3072bit key
- with password

![IMG_0379](https://user-images.githubusercontent.com/7940186/63907365-b5a08800-ca4d-11e9-800f-450b1debf6f9.PNG)

**Comment by jk234ert** [comment]
should be fixed in latest TestFlight version 1.1.5(26) [DMSGoPGP](https://github.com/DimensionDev/Tessercube-iOS/tree/feat/DMSGopenPGP)

**Comment by jk234ert** [comment]
@MainasuK close this issue when you confirm it fixed
