### ISSUE TITLE
Duplicate armored text shared by tessercube

### ISSUE THREAD

**Issue by jk234ert** [DimensionDev/Tessercube-iOS#54]
Affected version: App Store 1.1.4

Step to reproduce:
1. In tessercube, tap a private key in 'Me' tab, or a message in 'Message' tab.
2. Click 'Share public key' or 'export private key' or 'share encrypted message', in share activity view, click 'copy'
3. Switch to any IM app (telegram, etc..), paste the text 

Desired result:
Shared key/message armored text correctly pasted

Actual result:
**2** copies of shared key/message armored text pasted

**Comment by jk234ert** [comment]
Root cause:
Currently sharing implementation creates a temp file containing the same shared text, which means we are always sharing 2 items -- raw armored text, and a file with same content.

This implementation is added to make 'Airdrop' option always shown when the user shares something. A valid file URL could 'enable' Airdrop option.

After investigation, I found that 'Airdrop' disappears when the content to be shared is too large.
My solution is we put only 1 item in sharing -- a valid text file comes first, the raw content instead if we fail to create a temp valid text file.

**Comment by MainasuK** [comment]
> After investigation, I found that 'Airdrop' disappears when the content to be shared is too large.

What condition could cause AirDrop not appear?

**Comment by MainasuK** [comment]
Now I'm not sure that fix could work as expected.

- The item shared is one txt file.
- The most app could accept file could handle it and save or transfer as a file. 
- We expect the item we sharing is plain text PGP message.

AirDrop in iOS 12 somehow could not handle the long message. But iOS 13 always provide plaintext preview and AirDrop supports. That's what we need.

So maybe we need rollback to plaintext sharing without file.

**Comment by jk234ert** [comment]
To share armored public key and encrypted messages in plaintext could be fine.
How about `only sharing txt file for exporting private keys`? An exported private key file seems to be a reasonable result for user to backup and store the private keys.

**Comment by MainasuK** [comment]
It makes sense. So we only share the file item for the private key. Otherwise, share plaintext and do not consider AirDrop on iOS 12. 

I'll push the iOS 13 branch and create a new release branch today later. And fix it in that branch. Maybe we could seed GM TestFlight later this week.
