### ISSUE TITLE
When adding contact public key - "Import Keypair" is dimmed and not working 

### ISSUE THREAD

**Issue by Nock-zz** [DimensionDev/Tessercube-iOS#57]
Using iphone 6

Using Contact tab and pressing +

Unable to add public key  - "Import Keypair" is dimmed and not working

**Comment by neruthes** [comment]
Well... *It works on my machine*.

I cannot find any problem importing. My version is 1.1.5 (29) on TestFlight. Expect the next release to be operational.

Also let me see whether we may have a public TestFlight subscription link.

**Comment by Nock-zz** [comment]
Hmm looks like I have screwed up the install.  I have just downloaded directly from the Apple app store and I am not using testflight with Tessercube.

**Comment by MainasuK** [comment]
You can import other's PGP public key by tap the "+" button in the Contacts tab.
And The "Import Keypair" button is disabled until you input something in the text field.

**Comment by Tedko** [comment]
> Using iphone 6
> 
> Using Contact tab and pressing +
> 
> Unable to add public key - "Import Keypair" is dimmed and not working

It should able to auto detect your 'clipboard' content (if you copy someone's pub key)

**Comment by MainasuK** [comment]
Closed.

Feel free to reopen the issue if you still have problems.

**Comment by Nock-zz** [comment]
*And The "Import Keypair" button is disabled until you input something in
the text field.*


Yes - my mistake. When I copy a key then the Import Keypair button becomes
enabled and it works fine.

Thanks,


Nick
