### ISSUE TITLE
[Feature]Export contact's (such as Alice) pub key

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Tessercube-iOS#58]
Should be a necessary functionality for most PGP users.

**Comment by neruthes** [comment]
Should be easy. Let it be scheduled.

**Comment by yisiliu** [comment]
Since we are about to start our main development of Tessercube, shall we adopt github project too?

**Comment by neruthes** [comment]
<img width="448" alt="Screen Shot 2019-09-17 at 12 00 20" src="https://user-images.githubusercontent.com/2139261/65039930-d53b1a00-d942-11e9-846a-536b21ab4de5.png">

One button here should be enough. After tapping the button, the public key should be put into the clipboard and the user will see a self-dismissing alert telling him that it is already put into the clipboard.

The alert should look like the one which is used in App Store to tell the user that his rating is received by App Store, with title `Copied` and subtitle `Paste the public key anywhere.`.

![IMG_9839](https://user-images.githubusercontent.com/2139261/65040066-1c290f80-d943-11e9-8deb-b567674f1b84.PNG)

**Comment by Tedko** [comment]
👍

**Comment by Tedko** [comment]
Let’s do GitHub Proj. However please use trello for all marketing and bd
related topics

**Comment by neruthes** [comment]
Up<img width="467" alt="Screen Shot 2019-09-25 at 08 50 02" src="https://user-images.githubusercontent.com/2139261/65585185-9542eb00-df71-11e9-9e1f-19c6aa40a723.png">

Minor update on UI.

By invoking the export, an ActivityView should be promoted.

Refer to Sketch file for detailed parameters.

:)
