### ISSUE TITLE
Composed message not add sender as recipient

### ISSUE THREAD

**Issue by MainasuK** [DimensionDev/Tessercube-iOS#62]
When composing a message with the sender the encryption operator should add the sender in the recipient list. If not, the sender could not interpret it except the message already in the database.

**Comment by jk234ert** [comment]
Should we also hide the sender in the recipient picking view?

**Comment by MainasuK** [comment]
We opt-in set all private keys we have when composing messages via *Keyboard*. (like Android implement). But we now use the auto chose the first key as a sender. 

Compose message in the main app not use hidden recipient. Let the user chose the sender to sign.
