### ISSUE TITLE
Interpret message process enhancement

### ISSUE THREAD

**Issue by MainasuK** [DimensionDev/Tessercube-iOS#63]
Not burst force loop all private key to decrypt the message. Use message encryption key id and find the matching keys to decrypting like BCPGP.  

(Not sure if we resolve it already. Just mark it as a note.

**Comment by jk234ert** [comment]
#64

**Comment by MainasuK** [comment]
The [previours](https://github.com/DimensionDev/Tessercube-iOS/blob/abca0bdf403c08ce3762065be494cbbec63aba47/TesserCube/Crypto/KeyFactory%2BBCOpenPGP.swift) version decrypt process checks the decryption key if we have or not. (
Now we loop all key try to decrypt. It just works.

The KeyID is identification for key pair to aid cipher & signature. Fingerprint or long ID / short ID is hash for primary signing key. So signature key should use key ID to matching.

https://github.com/DimensionDev/Tessercube-iOS/blob/d81cc5f449810e0e6de0e98e641c6cce0ee54fa4/TesserCube/Crypto/KeyFactory%2BBCOpenPGP.swift#L142-L149

https://github.com/DimensionDev/Tessercube-iOS/pull/11#discussion_r294037967

**Comment by MainasuK** [comment]
Resolved issue.
