### ISSUE TITLE
Cleartext message not require public key to interpret

### ISSUE THREAD

**Issue by MainasuK** [DimensionDev/Tessercube-iOS#64]
The cleartext message should be interpreted without the signer public key and mark message not verified like the BCPGP version. Mark sender key shortID green when verified.

**Comment by MainasuK** [comment]
@jk234ert 

Could we port the `ReadMessage` method from `crypto/openpgp/read`. Now we missing the message meta info like signer meta and encrypted key id. (a.k.a `MessageDetails`)

https://github.com/ProtonMail/crypto/blob/ac9b7da05e531a5f03ab97c909e6b3c41dfca6dd/openpgp/read.go#L86

**Comment by jk234ert** [comment]
MessageDetail already ported for `PGPMessage`, 'ClearTextMessage` and 'PlainMessage' by calling [getMessageDetails()](https://github.com/DimensionDev/gopenpgp/blob/master/dist/iOS/DMSGoPGP.framework/Versions/A/Headers/Crypto.objc.h#L91)
Current implementationin develop branch is using decryption mechanism as mentioned in #63.

Let's have more test :)

**Comment by MainasuK** [comment]
> calling [getMessageDetails()](https://github.com/DimensionDev/gopenpgp/blob/master/dist/iOS/DMSGoPGP.framework/Versions/A/Headers/Crypto.objc.h#L91)

`- (CryptoMessageDetail* _Nullable)getMessageDetails:(CryptoKeyRing* _Nullable)keyRing error:(NSError* _Nullable* _Nullable)error;`

Could we pass in `nil` when the user not has any sender public key and extract the singer KeyID & UserID? Cleartext message is not needs decrypted to extract meta from the signature.

**Comment by MainasuK** [comment]
Resolved in 3bbbf0f
