### ISSUE TITLE
Search box in 'Contact' should follow the system default 'Phone'

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Tessercube-iOS#8]
<img src="https://user-images.githubusercontent.com/6687437/58765940-23eac100-85ab-11e9-874b-29f464098be7.PNG" alt="drawing" width="200"/><img src="https://user-images.githubusercontent.com/6687437/58765941-251bee00-85ab-11e9-8a31-212464e811cd.jpeg" alt="drawing" width="200"/>

Let's follow the system default design.

_Not sure about android side, will have a separate discussion later_

**Comment by neruthes** [comment]
But it is not Contacts; it is Phone.

**Comment by neruthes** [comment]
No. It should not follow Phone. It should follow Contacts.

**Comment by neruthes** [comment]
related: https://github.com/DimensionDev/Tessercube-Meta/issues/34
