### ISSUE TITLE
PRD Consolidation: Cryptocurrency Features [Draft]

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Tessercube-iOS#87]
# Abstract

# Objectives

# Use Cases

- [x] Create Wallet (Mnemonic Words only)
- [x] Backup Wallet (Mnemonic Words only)
- [x] Import Wallet (Mnemonic Words only)
- [x] See Wallet Status:
  - Nickname (`Map: WalletAddress => WalletAddress.slice(0, 6)`)
  - Current Balance
  - Wallet Address
- [x] Delete Wallet
- [x] See Tokens List
- [x] Add Token to Tokens List
  - Add pre-defined token
  - Add custom token
- [x] Delete Token in Tokens List
- [x] Create Red Packet
  - 2 Modes (Average & Random)
  - Select Wallet
  - Select Token
  - Specify Amount
  - Specify Shares
  - Sender Nickname (\<String>, Single-Line, Max 30 chars, cannot be empty)
  - Message (\<String>, Single-Line, Max 140 chars, can be empty)
- [x] Share Red Packet (excluding incoming ones)
- [x] Claim Red Packet (Including outgoing ones)
  - Choose Wallet
- [x] Refund Red Packet
- [x] View List of Red Packets (Per-Wallet only)
  - Incoming Red Packet
  - Outgoing Red Packet
- [x] View Red Packet Summary
  - Name
  - Total Amount
  - Actual Amount (claimed or refunded)
  - Creation time
    - `X hr ago` if within 24 hours
    - `X day(s) ago` if within 7 days
    - otherwise `yyyy-MM-DD`
  - Reception time (same standard as above)
- [x] View Red Packet Details
  - Total amount
  - Total shares
  - Available shares
  - List of collectors
    - Nickname
    - Wallet address
- [ ] Get "Get Refunded" Advice (In-App Banner)
- [x] Send Red Packet in Keyboard
  - Create (Invoke Smart Contract; Generate Hint Payload)
  - Share Hint Payload (Push into app text buffer & Copy to clipboard)
- [ ] Claim Red Packet in Keyboard

# Workflow: Send Red Packet

- Navigate to "Wallet" tab.
- Tap "Send Red Packet" button; navigate into "Red Packet Creation Page".
- Specify Mode, Amount, Wallet, Name, and Message.
- Tap "Send %f ETH" button; navigation into "Red Packet Detail Page".
- Tap "Done" button; exit "Red Packet Detail Page". Alternatively, wait here till the red packet is published (skipping the following 2 steps).
- Wait till the in-app banner appears or the push notification appears.
- Tap the in-app banner or the push notification; navigation into "Red Packet Detail Page".
- Tap "Share" button; open an ActivityView.
- End.

# Component: Red Packet Detail Page

## Mode: Outgoing Red Packet + Collectable

Available actions:

- Share
- Get Refunded

## Mode: Outgoing Red Packet + Uncollectible

Use for:

- PUBLISH_IN_PROGRESS
- ONLINE_OUT_OF_STOCK

Available actions:

- ...

## Mode: Incoming Red Packet + Collectable

Available actions:

- Share
- Open

## Mode: Incoming Red Packet + Uncollectible

Available actions:

- ...

**Comment by MainasuK** [comment]
Question:
https://github.com/DimensionDev/Tessercube-iOS/pull/91#discussion_r358756066

PRD defined:
> Sender Nickname (<String>, Single-Line, Max 30 chars)
> Message (<String>, Single-Line, Max 140 chars)

And should add verification requirements for the `sender_name` field.
For example, can we accept the *empty* name or only *blank* chars name?

**Comment by neruthes** [comment]
I think space 0x20 characters should be allowed, while tab and CR/LF may not be allowed. Generally, this field would impose the same requirement of generic input elements in HTML; strange characters like CR/LF will be prevented from being appended into the text field and will be filtered out when pasting. Additionally, empty string may not be allowed.

For error handling, we have two options:

- Show alert when tapping the creation button
- Use string "Anonymous" automatically

Both options look good to me. If there is no time for finding the optimal solution, we may use the 2nd option.

**Comment by MainasuK** [comment]
> Additionally, empty string may not be allowed.

Update `sender_name` note in wiki (2019-12-19): 
https://github.com/DimensionDev/Tessercube-iOS/wiki/Red-Packet-Data-Dictionary

@jk234ert @yisiliu @Tlaster

**Comment by neruthes** [comment]
Sorry, I focused on `Name` too much and forgot `Message`. Empty string should be allowed for `Message`.

**Comment by MainasuK** [comment]
Make sense. Wiki Updated. 
Allow trimmed message empty input for `send_message`.

**Comment by neruthes** [comment]
I would also suggest that any whitespace-like character (`\n`, `&nbsp;`, tab...) may be replaced with a real whitespace (`0x20`).

-----------

Some systems simply ignore them; as a result, a linebreak like...

```
Hello.
World.
```

... will become `Hello.World.` while it is supposed to become `Hello. World`.

Some writing systems (zh, ja) do not need a whitespace character to separate sentences, while some others (ko, en, ru, fr, de, es, it...) need.

If it is easy to detect system language setting, the sentence aggregating mechanism can work like:

```
function (paragraphs) { // Array<String>
    if (['zh', 'ja'].indexOf(system.language.slice(0,2)) !== -1) {
        // Is `zh` or `ja`
        return paragraphs.join('');
    } else {
        // Is another language
        return paragraphs.join(' ');
    }
}
```

Language-specific paragraph aggregation can be unnecessary for now; let this be noted for future references.

**Comment by neruthes** [comment]
# Note: List of states of component RedPacketCell instance (for Interaction Design)

## Outgoing

State | Action | Next State
----- | -------- | ------------
Detected | - | -
Claiming | (auto) | Claimed, Partially Claimed \| Claimed, Partially Claimed | - | -
Error, Malformed Red Packet | - | -
Error, Network Error | Retry | Claiming | - | -
Claimed, Partially Claimed | - | -
Claimed, Fully Claimed | - | -
Failure, Too Late | - | -
Failure, All Gone | - | -
Failure, Insufficient Gas | Retry | Claiming | - | -

## Incoming

State | Action | Next State
----- | -------- | ------------
Publishing | (auto) | Published, New
Error, Network Error | Retry | Publishing
Failure, Insufficient Gas | Retry | Publishing
Published, New | - | -
Published, Partially Claimed | - | -
Published, Fully Claimed | - | -
Expired | Get Refunded | Refunding | - | -
Refunding | (auto) | Refunded | - | -
Refunding Error, Network Error | Retry | Refunding | - | -
Refunding Failure, Insufficient Gas | Retry  | Refunding | - | -
Refunded | - | -

**Comment by MainasuK** [comment]
Use Cases list updated.

Not implement cases:
- Get "Get Refunded" Advice (In-App Banner)
- Claim Red Packet in Keyboard

Basically this feature is implemented. Open a new issue or re-open this issue if any feature request needs.
