### ISSUE TITLE
Decryption card in the keyboard text not visible under the dark mode

### ISSUE THREAD

**Issue by MainasuK** [DimensionDev/Tessercube-iOS#98]
The text color in the decryption card in the keyboard adapts the dark mode. The text color is white in the white background. We should specify the text color to fix the visibility issue.

**Comment by MainasuK** [comment]
@jk234ert 
That fix 902781b5a060bad68b6bdaf0364d9631052698f6 merges into fix/upstream-bugfix. And needs PR for RedPacket branch.

**Comment by jk234ert** [comment]
902781b merged into RedPacket within #102
